name: eats_vancouver
description: Discover new restaurants, happy hours & social deals in Vancouver, BC.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^13.2.1

  # Google Fonts
  google_fonts: ^6.2.1

  # Sharing
  share_plus: ^9.0.0

  # Icons & UI
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1

  # Utilities
  uuid: ^4.3.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
